// Do not edit. This file is machine generated by the Resource DLL Wizard.

library Project1;

{ITE} {LCID:00000419:00000809} {}
{ITE} {DFMFileType} {Unit1.dfm}
{ITE} {DFMFileType} {Unit2.dfm}
{ITE} {RCFileType} {Project1_DRC.rc}

{$R 'Unit1.dfm' Form1:TForm}
{$R 'Unit2.dfm' Form2:TForm}
{$R 'Project1_DRC.res' 'Project1_DRC.rc'}

{$E ENG}

begin
end.