# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Virusya\Kursova_2\windows\mainWindow.ui'
#
# Created: Sun Dec 16 16:16:09 2012
#      by: PyQt4 UI code generator 4.9.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_ElectronicLibrarian(object):
    def setupUi(self, ElectronicLibrarian):
        ElectronicLibrarian.setObjectName(_fromUtf8("ElectronicLibrarian"))
        ElectronicLibrarian.resize(614, 469)
        ElectronicLibrarian.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.centralwidget = QtGui.QWidget(ElectronicLibrarian)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.SourseList = QtGui.QTabWidget(self.centralwidget)
        self.SourseList.setGeometry(QtCore.QRect(10, 20, 391, 201))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.SourseList.setFont(font)
        self.SourseList.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.SourseList.setMouseTracking(False)
        self.SourseList.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.SourseList.setAcceptDrops(False)
        self.SourseList.setAutoFillBackground(False)
        self.SourseList.setTabShape(QtGui.QTabWidget.Rounded)
        self.SourseList.setDocumentMode(False)
        self.SourseList.setTabsClosable(False)
        self.SourseList.setMovable(True)
        self.SourseList.setObjectName(_fromUtf8("SourseList"))
        self.Books_tab = QtGui.QWidget()
        self.Books_tab.setObjectName(_fromUtf8("Books_tab"))
        self.BookList = QtGui.QTableWidget(self.Books_tab)
        self.BookList.setGeometry(QtCore.QRect(0, 0, 386, 173))
        self.BookList.setLocale(QtCore.QLocale(QtCore.QLocale.Ukrainian, QtCore.QLocale.Ukraine))
        self.BookList.setRowCount(0)
        self.BookList.setObjectName(_fromUtf8("BookList"))
        self.BookList.setColumnCount(3)
        item = QtGui.QTableWidgetItem()
        self.BookList.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.BookList.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.BookList.setHorizontalHeaderItem(2, item)
        self.BookList.horizontalHeader().setDefaultSectionSize(180)
        self.BookList.horizontalHeader().setMinimumSectionSize(190)
        self.BookList.verticalHeader().setDefaultSectionSize(25)
        self.SourseList.addTab(self.Books_tab, _fromUtf8(""))
        self.AddBooksSourse_button = QtGui.QPushButton(self.centralwidget)
        self.AddBooksSourse_button.setGeometry(QtCore.QRect(10, 220, 141, 31))
        self.AddBooksSourse_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.AddBooksSourse_button.setObjectName(_fromUtf8("AddBooksSourse_button"))
        self.RemoveBooksSourse_button = QtGui.QPushButton(self.centralwidget)
        self.RemoveBooksSourse_button.setGeometry(QtCore.QRect(150, 220, 121, 31))
        self.RemoveBooksSourse_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.RemoveBooksSourse_button.setObjectName(_fromUtf8("RemoveBooksSourse_button"))
        self.RemoveKeyword_button = QtGui.QPushButton(self.centralwidget)
        self.RemoveKeyword_button.setGeometry(QtCore.QRect(430, 220, 171, 31))
        self.RemoveKeyword_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.RemoveKeyword_button.setObjectName(_fromUtf8("RemoveKeyword_button"))
        self.AddKeyword = QtGui.QPushButton(self.centralwidget)
        self.AddKeyword.setGeometry(QtCore.QRect(430, 10, 91, 31))
        self.AddKeyword.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.AddKeyword.setObjectName(_fromUtf8("AddKeyword"))
        self.Investigate_Btn = QtGui.QPushButton(self.centralwidget)
        self.Investigate_Btn.setGeometry(QtCore.QRect(270, 220, 131, 31))
        self.Investigate_Btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Investigate_Btn.setObjectName(_fromUtf8("Investigate_Btn"))
        self.FindKeywordInDatabase_Btn = QtGui.QPushButton(self.centralwidget)
        self.FindKeywordInDatabase_Btn.setGeometry(QtCore.QRect(520, 10, 81, 31))
        self.FindKeywordInDatabase_Btn.setObjectName(_fromUtf8("FindKeywordInDatabase_Btn"))
        self.KeywordList = QtGui.QTableWidget(self.centralwidget)
        self.KeywordList.setGeometry(QtCore.QRect(430, 40, 171, 181))
        self.KeywordList.setRowCount(0)
        self.KeywordList.setObjectName(_fromUtf8("KeywordList"))
        self.KeywordList.setColumnCount(1)
        item = QtGui.QTableWidgetItem()
        self.KeywordList.setHorizontalHeaderItem(0, item)
        self.KeywordList.horizontalHeader().setDefaultSectionSize(120)
        self.KeywordList.horizontalHeader().setMinimumSectionSize(120)
        self.KeywordList.verticalHeader().setDefaultSectionSize(25)
        self.ShowResults_Btn = QtGui.QPushButton(self.centralwidget)
        self.ShowResults_Btn.setGeometry(QtCore.QRect(10, 260, 101, 33))
        self.ShowResults_Btn.setObjectName(_fromUtf8("ShowResults_Btn"))
        self.ResultList = QtGui.QTableWidget(self.centralwidget)
        self.ResultList.setGeometry(QtCore.QRect(10, 300, 591, 104))
        self.ResultList.setLocale(QtCore.QLocale(QtCore.QLocale.Ukrainian, QtCore.QLocale.Ukraine))
        self.ResultList.setRowCount(0)
        self.ResultList.setObjectName(_fromUtf8("ResultList"))
        self.ResultList.setColumnCount(3)
        item = QtGui.QTableWidgetItem()
        self.ResultList.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.ResultList.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.ResultList.setHorizontalHeaderItem(2, item)
        self.ResultList.horizontalHeader().setDefaultSectionSize(180)
        self.ResultList.horizontalHeader().setMinimumSectionSize(180)
        self.ResultList.verticalHeader().setDefaultSectionSize(25)
        ElectronicLibrarian.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(ElectronicLibrarian)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 614, 26))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuMain = QtGui.QMenu(self.menubar)
        self.menuMain.setObjectName(_fromUtf8("menuMain"))
        self.menuImport_spase = QtGui.QMenu(self.menuMain)
        self.menuImport_spase.setObjectName(_fromUtf8("menuImport_spase"))
        self.menuBook_page = QtGui.QMenu(self.menuImport_spase)
        self.menuBook_page.setObjectName(_fromUtf8("menuBook_page"))
        self.menuDatabase = QtGui.QMenu(self.menubar)
        self.menuDatabase.setObjectName(_fromUtf8("menuDatabase"))
        self.menuShow_list_of = QtGui.QMenu(self.menuDatabase)
        self.menuShow_list_of.setObjectName(_fromUtf8("menuShow_list_of"))
        self.menuSort_by = QtGui.QMenu(self.menuDatabase)
        self.menuSort_by.setObjectName(_fromUtf8("menuSort_by"))
        self.menuKeyword = QtGui.QMenu(self.menubar)
        self.menuKeyword.setObjectName(_fromUtf8("menuKeyword"))
        self.menuAdd_new = QtGui.QMenu(self.menuKeyword)
        self.menuAdd_new.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.menuAdd_new.setObjectName(_fromUtf8("menuAdd_new"))
        self.menuDetete = QtGui.QMenu(self.menuKeyword)
        self.menuDetete.setObjectName(_fromUtf8("menuDetete"))
        self.menuCorrect = QtGui.QMenu(self.menuKeyword)
        self.menuCorrect.setObjectName(_fromUtf8("menuCorrect"))
        self.menuFind = QtGui.QMenu(self.menubar)
        self.menuFind.setObjectName(_fromUtf8("menuFind"))
        self.menuIn_books = QtGui.QMenu(self.menuFind)
        self.menuIn_books.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.menuIn_books.setObjectName(_fromUtf8("menuIn_books"))
        self.menuIn_online_books = QtGui.QMenu(self.menuFind)
        self.menuIn_online_books.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.menuIn_online_books.setObjectName(_fromUtf8("menuIn_online_books"))
        self.menuIn_Internet = QtGui.QMenu(self.menuFind)
        self.menuIn_Internet.setObjectName(_fromUtf8("menuIn_Internet"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        ElectronicLibrarian.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(ElectronicLibrarian)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        ElectronicLibrarian.setStatusBar(self.statusbar)
        self.actionRecommended_sourse = QtGui.QAction(ElectronicLibrarian)
        self.actionRecommended_sourse.setObjectName(_fromUtf8("actionRecommended_sourse"))
        self.actionAbout_program = QtGui.QAction(ElectronicLibrarian)
        self.actionAbout_program.setObjectName(_fromUtf8("actionAbout_program"))
        self.actionAbout_autor = QtGui.QAction(ElectronicLibrarian)
        self.actionAbout_autor.setObjectName(_fromUtf8("actionAbout_autor"))
        self.actionKeyword = QtGui.QAction(ElectronicLibrarian)
        self.actionKeyword.setObjectName(_fromUtf8("actionKeyword"))
        self.actionKeyword_2 = QtGui.QAction(ElectronicLibrarian)
        self.actionKeyword_2.setObjectName(_fromUtf8("actionKeyword_2"))
        self.actionKeyword_3 = QtGui.QAction(ElectronicLibrarian)
        self.actionKeyword_3.setObjectName(_fromUtf8("actionKeyword_3"))
        self.actionWord_combinations = QtGui.QAction(ElectronicLibrarian)
        self.actionWord_combinations.setObjectName(_fromUtf8("actionWord_combinations"))
        self.actionWord_combinations_2 = QtGui.QAction(ElectronicLibrarian)
        self.actionWord_combinations_2.setObjectName(_fromUtf8("actionWord_combinations_2"))
        self.actionWord_combinations_3 = QtGui.QAction(ElectronicLibrarian)
        self.actionWord_combinations_3.setObjectName(_fromUtf8("actionWord_combinations_3"))
        self.actionSentens = QtGui.QAction(ElectronicLibrarian)
        self.actionSentens.setObjectName(_fromUtf8("actionSentens"))
        self.actionSentens_2 = QtGui.QAction(ElectronicLibrarian)
        self.actionSentens_2.setObjectName(_fromUtf8("actionSentens_2"))
        self.actionSentens_3 = QtGui.QAction(ElectronicLibrarian)
        self.actionSentens_3.setObjectName(_fromUtf8("actionSentens_3"))
        self.actionKeyword_4 = QtGui.QAction(ElectronicLibrarian)
        self.actionKeyword_4.setObjectName(_fromUtf8("actionKeyword_4"))
        self.actionKeyword_5 = QtGui.QAction(ElectronicLibrarian)
        self.actionKeyword_5.setObjectName(_fromUtf8("actionKeyword_5"))
        self.actionKeyword_6 = QtGui.QAction(ElectronicLibrarian)
        self.actionKeyword_6.setObjectName(_fromUtf8("actionKeyword_6"))
        self.actionList_of_keywords = QtGui.QAction(ElectronicLibrarian)
        self.actionList_of_keywords.setObjectName(_fromUtf8("actionList_of_keywords"))
        self.actionList_of_keywords_2 = QtGui.QAction(ElectronicLibrarian)
        self.actionList_of_keywords_2.setObjectName(_fromUtf8("actionList_of_keywords_2"))
        self.actionList_of_keywords_3 = QtGui.QAction(ElectronicLibrarian)
        self.actionList_of_keywords_3.setObjectName(_fromUtf8("actionList_of_keywords_3"))
        self.actionAdd_database = QtGui.QAction(ElectronicLibrarian)
        self.actionAdd_database.setObjectName(_fromUtf8("actionAdd_database"))
        self.actionDelete = QtGui.QAction(ElectronicLibrarian)
        self.actionDelete.setObjectName(_fromUtf8("actionDelete"))
        self.actionDatabases = QtGui.QAction(ElectronicLibrarian)
        self.actionDatabases.setObjectName(_fromUtf8("actionDatabases"))
        self.actionKeywords_in_this_database = QtGui.QAction(ElectronicLibrarian)
        self.actionKeywords_in_this_database.setObjectName(_fromUtf8("actionKeywords_in_this_database"))
        self.actionKeywords = QtGui.QAction(ElectronicLibrarian)
        self.actionKeywords.setObjectName(_fromUtf8("actionKeywords"))
        self.actionNumbers = QtGui.QAction(ElectronicLibrarian)
        self.actionNumbers.setObjectName(_fromUtf8("actionNumbers"))
        self.actionSave_to = QtGui.QAction(ElectronicLibrarian)
        self.actionSave_to.setObjectName(_fromUtf8("actionSave_to"))
        self.actionSent_to = QtGui.QAction(ElectronicLibrarian)
        self.actionSent_to.setObjectName(_fromUtf8("actionSent_to"))
        self.actionOnline_book = QtGui.QAction(ElectronicLibrarian)
        self.actionOnline_book.setObjectName(_fromUtf8("actionOnline_book"))
        self.actionInternet_pages = QtGui.QAction(ElectronicLibrarian)
        self.actionInternet_pages.setObjectName(_fromUtf8("actionInternet_pages"))
        self.actionChoose_format = QtGui.QAction(ElectronicLibrarian)
        self.actionChoose_format.setObjectName(_fromUtf8("actionChoose_format"))
        self.actionNumber_of_the_page = QtGui.QAction(ElectronicLibrarian)
        self.actionNumber_of_the_page.setCheckable(False)
        self.actionNumber_of_the_page.setObjectName(_fromUtf8("actionNumber_of_the_page"))
        self.menuBook_page.addAction(self.actionChoose_format)
        self.menuBook_page.addAction(self.actionNumber_of_the_page)
        self.menuImport_spase.addAction(self.menuBook_page.menuAction())
        self.menuImport_spase.addAction(self.actionOnline_book)
        self.menuImport_spase.addAction(self.actionInternet_pages)
        self.menuMain.addAction(self.menuImport_spase.menuAction())
        self.menuMain.addAction(self.actionSave_to)
        self.menuMain.addAction(self.actionSent_to)
        self.menuShow_list_of.addAction(self.actionDatabases)
        self.menuShow_list_of.addAction(self.actionKeywords_in_this_database)
        self.menuSort_by.addAction(self.actionKeywords)
        self.menuSort_by.addAction(self.actionNumbers)
        self.menuDatabase.addAction(self.menuShow_list_of.menuAction())
        self.menuDatabase.addSeparator()
        self.menuDatabase.addAction(self.actionAdd_database)
        self.menuDatabase.addAction(self.actionDelete)
        self.menuDatabase.addSeparator()
        self.menuDatabase.addAction(self.menuSort_by.menuAction())
        self.menuAdd_new.addAction(self.actionKeyword_4)
        self.menuAdd_new.addAction(self.actionList_of_keywords)
        self.menuDetete.addAction(self.actionKeyword_5)
        self.menuDetete.addAction(self.actionList_of_keywords_2)
        self.menuCorrect.addAction(self.actionKeyword_6)
        self.menuCorrect.addAction(self.actionList_of_keywords_3)
        self.menuKeyword.addAction(self.menuAdd_new.menuAction())
        self.menuKeyword.addAction(self.menuDetete.menuAction())
        self.menuKeyword.addAction(self.menuCorrect.menuAction())
        self.menuIn_books.addAction(self.actionKeyword)
        self.menuIn_books.addAction(self.actionWord_combinations)
        self.menuIn_books.addAction(self.actionSentens)
        self.menuIn_online_books.addAction(self.actionKeyword_2)
        self.menuIn_online_books.addAction(self.actionWord_combinations_2)
        self.menuIn_online_books.addAction(self.actionSentens_2)
        self.menuIn_Internet.addAction(self.actionKeyword_3)
        self.menuIn_Internet.addAction(self.actionWord_combinations_3)
        self.menuIn_Internet.addAction(self.actionSentens_3)
        self.menuFind.addAction(self.menuIn_books.menuAction())
        self.menuFind.addSeparator()
        self.menuFind.addAction(self.menuIn_online_books.menuAction())
        self.menuFind.addSeparator()
        self.menuFind.addAction(self.menuIn_Internet.menuAction())
        self.menuHelp.addAction(self.actionRecommended_sourse)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout_program)
        self.menuHelp.addAction(self.actionAbout_autor)
        self.menubar.addAction(self.menuMain.menuAction())
        self.menubar.addAction(self.menuDatabase.menuAction())
        self.menubar.addAction(self.menuKeyword.menuAction())
        self.menubar.addAction(self.menuFind.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(ElectronicLibrarian)
        self.SourseList.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ElectronicLibrarian)

    def retranslateUi(self, ElectronicLibrarian):
        ElectronicLibrarian.setWindowTitle(QtGui.QApplication.translate("ElectronicLibrarian", "Electronic Librarian", None, QtGui.QApplication.UnicodeUTF8))
        self.BookList.setSortingEnabled(True)
        item = self.BookList.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("ElectronicLibrarian", "Book", None, QtGui.QApplication.UnicodeUTF8))
        item = self.BookList.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("ElectronicLibrarian", "Sourse", None, QtGui.QApplication.UnicodeUTF8))
        item = self.BookList.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("ElectronicLibrarian", "Status", None, QtGui.QApplication.UnicodeUTF8))
        self.SourseList.setTabText(self.SourseList.indexOf(self.Books_tab), QtGui.QApplication.translate("ElectronicLibrarian", "Books", None, QtGui.QApplication.UnicodeUTF8))
        self.AddBooksSourse_button.setText(QtGui.QApplication.translate("ElectronicLibrarian", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.RemoveBooksSourse_button.setText(QtGui.QApplication.translate("ElectronicLibrarian", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.RemoveKeyword_button.setText(QtGui.QApplication.translate("ElectronicLibrarian", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.AddKeyword.setText(QtGui.QApplication.translate("ElectronicLibrarian", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.Investigate_Btn.setText(QtGui.QApplication.translate("ElectronicLibrarian", "Investigate", None, QtGui.QApplication.UnicodeUTF8))
        self.FindKeywordInDatabase_Btn.setText(QtGui.QApplication.translate("ElectronicLibrarian", "Find", None, QtGui.QApplication.UnicodeUTF8))
        item = self.KeywordList.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("ElectronicLibrarian", "Keyword", None, QtGui.QApplication.UnicodeUTF8))
        self.ShowResults_Btn.setText(QtGui.QApplication.translate("ElectronicLibrarian", "Show Result", None, QtGui.QApplication.UnicodeUTF8))
        self.ResultList.setSortingEnabled(True)
        item = self.ResultList.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("ElectronicLibrarian", "Keyword", None, QtGui.QApplication.UnicodeUTF8))
        item = self.ResultList.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("ElectronicLibrarian", "Book", None, QtGui.QApplication.UnicodeUTF8))
        item = self.ResultList.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("ElectronicLibrarian", "Pages", None, QtGui.QApplication.UnicodeUTF8))
        self.menuMain.setTitle(QtGui.QApplication.translate("ElectronicLibrarian", "Main", None, QtGui.QApplication.UnicodeUTF8))
        self.menuImport_spase.setTitle(QtGui.QApplication.translate("ElectronicLibrarian", "import spase", None, QtGui.QApplication.UnicodeUTF8))
        self.menuBook_page.setTitle(QtGui.QApplication.translate("ElectronicLibrarian", "Book page", None, QtGui.QApplication.UnicodeUTF8))
        self.menuDatabase.setTitle(QtGui.QApplication.translate("ElectronicLibrarian", "Database", None, QtGui.QApplication.UnicodeUTF8))
        self.menuShow_list_of.setTitle(QtGui.QApplication.translate("ElectronicLibrarian", "show list of ", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSort_by.setTitle(QtGui.QApplication.translate("ElectronicLibrarian", "sort by", None, QtGui.QApplication.UnicodeUTF8))
        self.menuKeyword.setTitle(QtGui.QApplication.translate("ElectronicLibrarian", "Keyword", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAdd_new.setTitle(QtGui.QApplication.translate("ElectronicLibrarian", "add new", None, QtGui.QApplication.UnicodeUTF8))
        self.menuDetete.setTitle(QtGui.QApplication.translate("ElectronicLibrarian", "detete ", None, QtGui.QApplication.UnicodeUTF8))
        self.menuCorrect.setTitle(QtGui.QApplication.translate("ElectronicLibrarian", "correct ", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFind.setTitle(QtGui.QApplication.translate("ElectronicLibrarian", "Find", None, QtGui.QApplication.UnicodeUTF8))
        self.menuIn_books.setTitle(QtGui.QApplication.translate("ElectronicLibrarian", "in books", None, QtGui.QApplication.UnicodeUTF8))
        self.menuIn_online_books.setTitle(QtGui.QApplication.translate("ElectronicLibrarian", "in online books", None, QtGui.QApplication.UnicodeUTF8))
        self.menuIn_Internet.setTitle(QtGui.QApplication.translate("ElectronicLibrarian", "in Internet", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("ElectronicLibrarian", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRecommended_sourse.setText(QtGui.QApplication.translate("ElectronicLibrarian", "Recommended sourse", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout_program.setText(QtGui.QApplication.translate("ElectronicLibrarian", "About program", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout_autor.setText(QtGui.QApplication.translate("ElectronicLibrarian", "About autor", None, QtGui.QApplication.UnicodeUTF8))
        self.actionKeyword.setText(QtGui.QApplication.translate("ElectronicLibrarian", "keyword", None, QtGui.QApplication.UnicodeUTF8))
        self.actionKeyword_2.setText(QtGui.QApplication.translate("ElectronicLibrarian", "keyword", None, QtGui.QApplication.UnicodeUTF8))
        self.actionKeyword_3.setText(QtGui.QApplication.translate("ElectronicLibrarian", "keyword", None, QtGui.QApplication.UnicodeUTF8))
        self.actionWord_combinations.setText(QtGui.QApplication.translate("ElectronicLibrarian", "word combinations", None, QtGui.QApplication.UnicodeUTF8))
        self.actionWord_combinations_2.setText(QtGui.QApplication.translate("ElectronicLibrarian", "word combinations", None, QtGui.QApplication.UnicodeUTF8))
        self.actionWord_combinations_3.setText(QtGui.QApplication.translate("ElectronicLibrarian", "word combinations", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSentens.setText(QtGui.QApplication.translate("ElectronicLibrarian", "sentens", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSentens_2.setText(QtGui.QApplication.translate("ElectronicLibrarian", "sentens", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSentens_3.setText(QtGui.QApplication.translate("ElectronicLibrarian", "sentens", None, QtGui.QApplication.UnicodeUTF8))
        self.actionKeyword_4.setText(QtGui.QApplication.translate("ElectronicLibrarian", "keyword", None, QtGui.QApplication.UnicodeUTF8))
        self.actionKeyword_5.setText(QtGui.QApplication.translate("ElectronicLibrarian", "keyword", None, QtGui.QApplication.UnicodeUTF8))
        self.actionKeyword_6.setText(QtGui.QApplication.translate("ElectronicLibrarian", "keyword", None, QtGui.QApplication.UnicodeUTF8))
        self.actionList_of_keywords.setText(QtGui.QApplication.translate("ElectronicLibrarian", "list of keywords", None, QtGui.QApplication.UnicodeUTF8))
        self.actionList_of_keywords_2.setText(QtGui.QApplication.translate("ElectronicLibrarian", "list of keywords", None, QtGui.QApplication.UnicodeUTF8))
        self.actionList_of_keywords_3.setText(QtGui.QApplication.translate("ElectronicLibrarian", "list of keywords", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAdd_database.setText(QtGui.QApplication.translate("ElectronicLibrarian", "add database", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDelete.setText(QtGui.QApplication.translate("ElectronicLibrarian", "delete ", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDatabases.setText(QtGui.QApplication.translate("ElectronicLibrarian", "databases", None, QtGui.QApplication.UnicodeUTF8))
        self.actionKeywords_in_this_database.setText(QtGui.QApplication.translate("ElectronicLibrarian", "keywords in this database", None, QtGui.QApplication.UnicodeUTF8))
        self.actionKeywords.setText(QtGui.QApplication.translate("ElectronicLibrarian", "keywords", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNumbers.setText(QtGui.QApplication.translate("ElectronicLibrarian", "numbers", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_to.setText(QtGui.QApplication.translate("ElectronicLibrarian", "save to", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSent_to.setText(QtGui.QApplication.translate("ElectronicLibrarian", "sent to", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOnline_book.setText(QtGui.QApplication.translate("ElectronicLibrarian", "Online book", None, QtGui.QApplication.UnicodeUTF8))
        self.actionInternet_pages.setText(QtGui.QApplication.translate("ElectronicLibrarian", "Internet pages", None, QtGui.QApplication.UnicodeUTF8))
        self.actionChoose_format.setText(QtGui.QApplication.translate("ElectronicLibrarian", "choose format", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNumber_of_the_page.setText(QtGui.QApplication.translate("ElectronicLibrarian", "Book", None, QtGui.QApplication.UnicodeUTF8))

